common: &common
  # server won't do any authentication
  authentication_method: noauth
  
  # Uncomment the config property below if you want tpkg reporting server to use restful-authentication. 
  # You'll need to create config/initializers/sites_key.rb. See 
  # https://github.com/technoweenie/restful-authentication for more info for how to use that plugin
  # authentication_method: restful-authentication

  upload_path: /tmp/repo2/
  verify_upload: true  # if set to true, you also need to install tpkg client/lib
    
development: &non_production_env
  <<: *common
  
staging:
  <<: *non_production_env

production:
  <<: *common
